# src/config.yaml
# This is a sample configuration file

# COMP0158 - DSML Project

# Data
data:
  # Absolute path to the project's root directory
  # Change this name to the absolute path of the root directory on your machine.
  root_dir: /Volumes/Buffalo/UCL/COMP0158/codebase

  # Relative paths to the data directories
  raw_data:
    umls_2024: data/raw/2024AA-full/2024AA/
    medmentions_full_root: data/raw/MedMentions-master/full/data/
    medmentions_st21pv_root: data/raw/MedMentions-master/st21pv/data
  processed_data:
    medmentions_full: data/processed/medmentions_full_ner
    medmentions_st21pv: data/processed/medmentions_st21pv_ner
  interim_data: data/interim
  external_data: data/external

ner:
  model_name: "allenai/scibert_scivocab_uncased"
  batch_size: 64
  max_len: 128
  num_epochs: 10
  learning_rate: 0.0001
  max_grad_norm: 1.0
  num_workers: 24
  train_shuffle: True
  dropout_prob: 0.1
  model_path: models/ner/bert_ner.pt
  tokenizer_path: models/ner/bert_ner_tokenizer/

softmax_classifier:
  tensorflow_model_path: "models/Classifiers/softmax.cui.h5"
  pytorch_model_path: "models/Classifiers/softmax.cui.pt"
  label_mapping: "models/Classifiers/softmax.cui.map"
